<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE qalab [<!ELEMENT qalab (summary,file*)>
<!ATTLIST qalab version CDATA #REQUIRED>
<!ELEMENT summary (summaryresult*)>
<!ELEMENT file (result+)>
<!ATTLIST file id ID #REQUIRED>
<!ATTLIST file project CDATA #REQUIRED>
<!ATTLIST file module CDATA #REQUIRED>
<!ATTLIST file path CDATA #REQUIRED>
<!ELEMENT result EMPTY>
<!ATTLIST result date CDATA #REQUIRED>
<!ATTLIST result statvalue CDATA #REQUIRED>
<!ATTLIST result type CDATA #REQUIRED>
<!ELEMENT summaryresult EMPTY>
<!ATTLIST summaryresult project CDATA #REQUIRED>
<!ATTLIST summaryresult module CDATA #REQUIRED>
<!ATTLIST summaryresult date CDATA #REQUIRED>
<!ATTLIST summaryresult statvalue CDATA #REQUIRED>
<!ATTLIST summaryresult filecount CDATA #REQUIRED>
<!ATTLIST summaryresult type CDATA #REQUIRED>
]>
<qalab version="1.2">
    <summary>
        <summaryresult date="2006-11-14" filecount="121"
            module="statsvn" project="statsvn" statvalue="610" type="checkstyle"/>
        <summaryresult date="2006-11-14" filecount="34" module="statsvn"
            project="statsvn" statvalue="64" type="findbugs"/>
        <summaryresult date="2006-11-14" filecount="112"
            module="statsvn" project="statsvn" statvalue="69" type="cobertura-line"/>
        <summaryresult date="2006-11-14" filecount="112"
            module="statsvn" project="statsvn" statvalue="73" type="cobertura-branch"/>
        <summaryresult date="2006-11-14" filecount="8" module="statsvn"
            project="statsvn" statvalue="14" type="pmd"/>
        <summaryresult date="2006-11-15" filecount="121"
            module="statsvn" project="statsvn" statvalue="594" type="checkstyle"/>
        <summaryresult date="2006-11-15" filecount="30" module="statsvn"
            project="statsvn" statvalue="52" type="findbugs"/>
        <summaryresult date="2006-11-15" filecount="112"
            module="statsvn" project="statsvn" statvalue="69" type="cobertura-line"/>
        <summaryresult date="2006-11-15" filecount="112"
            module="statsvn" project="statsvn" statvalue="73" type="cobertura-branch"/>
        <summaryresult date="2006-11-15" filecount="6" module="statsvn"
            project="statsvn" statvalue="12" type="pmd"/>
        <summaryresult date="2006-11-16" filecount="121"
            module="statsvn" project="statsvn" statvalue="439" type="checkstyle"/>
        <summaryresult date="2006-11-16" filecount="30" module="statsvn"
            project="statsvn" statvalue="61" type="findbugs"/>
        <summaryresult date="2006-11-16" filecount="112"
            module="statsvn" project="statsvn" statvalue="68" type="cobertura-line"/>
        <summaryresult date="2006-11-16" filecount="112"
            module="statsvn" project="statsvn" statvalue="72" type="cobertura-branch"/>
        <summaryresult date="2006-11-16" filecount="7" module="statsvn"
            project="statsvn" statvalue="13" type="pmd"/>
        <summaryresult date="2006-11-17" filecount="121"
            module="statsvn" project="statsvn" statvalue="393" type="checkstyle"/>
        <summaryresult date="2006-11-17" filecount="29" module="statsvn"
            project="statsvn" statvalue="51" type="findbugs"/>
        <summaryresult date="2006-11-17" filecount="112"
            module="statsvn" project="statsvn" statvalue="68" type="cobertura-line"/>
        <summaryresult date="2006-11-17" filecount="112"
            module="statsvn" project="statsvn" statvalue="73" type="cobertura-branch"/>
        <summaryresult date="2006-11-17" filecount="7" module="statsvn"
            project="statsvn" statvalue="13" type="pmd"/>
        <summaryresult date="2006-11-18" filecount="122"
            module="statsvn" project="statsvn" statvalue="165" type="checkstyle"/>
        <summaryresult date="2006-11-18" filecount="27" module="statsvn"
            project="statsvn" statvalue="39" type="findbugs"/>
        <summaryresult date="2006-11-18" filecount="113"
            module="statsvn" project="statsvn" statvalue="68" type="cobertura-line"/>
        <summaryresult date="2006-11-18" filecount="113"
            module="statsvn" project="statsvn" statvalue="72" type="cobertura-branch"/>
        <summaryresult date="2006-11-18" filecount="6" module="statsvn"
            project="statsvn" statvalue="12" type="pmd"/>
        <summaryresult date="2006-11-19" filecount="122"
            module="statsvn" project="statsvn" statvalue="165" type="checkstyle"/>
        <summaryresult date="2006-11-19" filecount="26" module="statsvn"
            project="statsvn" statvalue="39" type="findbugs"/>
        <summaryresult date="2006-11-19" filecount="113"
            module="statsvn" project="statsvn" statvalue="68" type="cobertura-line"/>
        <summaryresult date="2006-11-19" filecount="113"
            module="statsvn" project="statsvn" statvalue="72" type="cobertura-branch"/>
        <summaryresult date="2006-11-19" filecount="6" module="statsvn"
            project="statsvn" statvalue="12" type="pmd"/>
        <summaryresult date="2006-11-20" filecount="32" module="statsvn"
            project="statsvn" statvalue="56" type="checkstyle"/>
        <summaryresult date="2006-11-20" filecount="11" module="statsvn"
            project="statsvn" statvalue="14" type="findbugs"/>
        <summaryresult date="2006-11-20" filecount="27" module="statsvn"
            project="statsvn" statvalue="62" type="cobertura-line"/>
        <summaryresult date="2006-11-20" filecount="27" module="statsvn"
            project="statsvn" statvalue="73" type="cobertura-branch"/>
        <summaryresult date="2006-11-20" filecount="6" module="statsvn"
            project="statsvn" statvalue="12" type="pmd"/>
        <summaryresult date="2006-11-22" filecount="36" module="statsvn"
            project="statsvn" statvalue="27" type="checkstyle"/>
        <summaryresult date="2006-11-22" filecount="2" module="statsvn"
            project="statsvn" statvalue="2" type="findbugs"/>
        <summaryresult date="2006-11-22" filecount="31" module="statsvn"
            project="statsvn" statvalue="60" type="cobertura-line"/>
        <summaryresult date="2006-11-22" filecount="31" module="statsvn"
            project="statsvn" statvalue="73" type="cobertura-branch"/>
        <summaryresult date="2006-11-22" filecount="3" module="statsvn"
            project="statsvn" statvalue="9" type="pmd"/>
        <summaryresult date="2006-11-23" filecount="36" module="statsvn"
            project="statsvn" statvalue="24" type="checkstyle"/>
        <summaryresult date="2006-11-23" filecount="1" module="statsvn"
            project="statsvn" statvalue="1" type="findbugs"/>
        <summaryresult date="2006-11-23" filecount="31" module="statsvn"
            project="statsvn" statvalue="61" type="cobertura-line"/>
        <summaryresult date="2006-11-23" filecount="31" module="statsvn"
            project="statsvn" statvalue="74" type="cobertura-branch"/>
        <summaryresult date="2006-11-23" filecount="3" module="statsvn"
            project="statsvn" statvalue="9" type="pmd"/>
        <summaryresult date="2006-11-24" filecount="36" module="statsvn"
            project="statsvn" statvalue="25" type="checkstyle"/>
        <summaryresult date="2006-11-24" filecount="1" module="statsvn"
            project="statsvn" statvalue="1" type="findbugs"/>
        <summaryresult date="2006-11-24" filecount="31" module="statsvn"
            project="statsvn" statvalue="62" type="cobertura-line"/>
        <summaryresult date="2006-11-24" filecount="31" module="statsvn"
            project="statsvn" statvalue="74" type="cobertura-branch"/>
        <summaryresult date="2006-11-24" filecount="3" module="statsvn"
            project="statsvn" statvalue="9" type="pmd"/>
        <summaryresult date="2006-11-27" filecount="36" module="statsvn"
            project="statsvn" statvalue="25" type="checkstyle"/>
        <summaryresult date="2006-11-27" filecount="1" module="statsvn"
            project="statsvn" statvalue="1" type="findbugs"/>
        <summaryresult date="2006-11-27" filecount="31" module="statsvn"
            project="statsvn" statvalue="62" type="cobertura-line"/>
        <summaryresult date="2006-11-27" filecount="31" module="statsvn"
            project="statsvn" statvalue="74" type="cobertura-branch"/>
        <summaryresult date="2006-11-27" filecount="3" module="statsvn"
            project="statsvn" statvalue="9" type="pmd"/>
        <summaryresult date="2006-11-28" filecount="36" module="statsvn"
            project="statsvn" statvalue="25" type="checkstyle"/>
        <summaryresult date="2006-11-28" filecount="1" module="statsvn"
            project="statsvn" statvalue="1" type="findbugs"/>
        <summaryresult date="2006-11-28" filecount="31" module="statsvn"
            project="statsvn" statvalue="62" type="cobertura-line"/>
        <summaryresult date="2006-11-28" filecount="31" module="statsvn"
            project="statsvn" statvalue="74" type="cobertura-branch"/>
        <summaryresult date="2006-11-28" filecount="3" module="statsvn"
            project="statsvn" statvalue="9" type="pmd"/>
        <summaryresult date="2006-12-03" filecount="37" module="statsvn"
            project="statsvn" statvalue="44" type="checkstyle"/>
        <summaryresult date="2006-12-03" filecount="1" module="statsvn"
            project="statsvn" statvalue="1" type="findbugs"/>
        <summaryresult date="2006-12-03" filecount="1" module="statsvn"
            project="statsvn" statvalue="26" type="simian"/>
        <summaryresult date="2006-12-03" filecount="32" module="statsvn"
            project="statsvn" statvalue="56" type="cobertura-line"/>
        <summaryresult date="2006-12-03" filecount="32" module="statsvn"
            project="statsvn" statvalue="66" type="cobertura-branch"/>
        <summaryresult date="2006-12-03" filecount="3" module="statsvn"
            project="statsvn" statvalue="9" type="pmd"/>
        <summaryresult date="2006-12-04" filecount="39" module="statsvn"
            project="statsvn" statvalue="65" type="checkstyle"/>
        <summaryresult date="2006-12-04" filecount="3" module="statsvn"
            project="statsvn" statvalue="3" type="findbugs"/>
        <summaryresult date="2006-12-04" filecount="1" module="statsvn"
            project="statsvn" statvalue="26" type="simian"/>
        <summaryresult date="2006-12-04" filecount="34" module="statsvn"
            project="statsvn" statvalue="55" type="cobertura-line"/>
        <summaryresult date="2006-12-04" filecount="34" module="statsvn"
            project="statsvn" statvalue="66" type="cobertura-branch"/>
        <summaryresult date="2006-12-04" filecount="5" module="statsvn"
            project="statsvn" statvalue="14" type="pmd"/>
        <summaryresult date="2006-12-05" filecount="40" module="statsvn"
            project="statsvn" statvalue="78" type="checkstyle"/>
        <summaryresult date="2006-12-05" filecount="2" module="statsvn"
            project="statsvn" statvalue="2" type="findbugs"/>
        <summaryresult date="2006-12-05" filecount="1" module="statsvn"
            project="statsvn" statvalue="26" type="simian"/>
        <summaryresult date="2006-12-05" filecount="35" module="statsvn"
            project="statsvn" statvalue="52" type="cobertura-line"/>
        <summaryresult date="2006-12-05" filecount="35" module="statsvn"
            project="statsvn" statvalue="63" type="cobertura-branch"/>
        <summaryresult date="2006-12-05" filecount="7" module="statsvn"
            project="statsvn" statvalue="18" type="pmd"/>
        <summaryresult date="2006-12-10" filecount="36" module="statsvn"
            project="statsvn" statvalue="38" type="checkstyle"/>
        <summaryresult date="2006-12-10" filecount="2" module="statsvn"
            project="statsvn" statvalue="2" type="findbugs"/>
        <summaryresult date="2006-12-10" filecount="1" module="statsvn"
            project="statsvn" statvalue="26" type="simian"/>
        <summaryresult date="2006-12-10" filecount="35" module="statsvn"
            project="statsvn" statvalue="54" type="cobertura-line"/>
        <summaryresult date="2006-12-10" filecount="35" module="statsvn"
            project="statsvn" statvalue="65" type="cobertura-branch"/>
        <summaryresult date="2006-12-10" filecount="4" module="statsvn"
            project="statsvn" statvalue="12" type="pmd"/>
        <summaryresult date="2006-12-11" filecount="37" module="statsvn"
            project="statsvn" statvalue="49" type="checkstyle"/>
        <summaryresult date="2006-12-11" filecount="2" module="statsvn"
            project="statsvn" statvalue="2" type="findbugs"/>
        <summaryresult date="2006-12-11" filecount="1" module="statsvn"
            project="statsvn" statvalue="26" type="simian"/>
        <summaryresult date="2006-12-11" filecount="32" module="statsvn"
            project="statsvn" statvalue="58" type="cobertura-line"/>
        <summaryresult date="2006-12-11" filecount="32" module="statsvn"
            project="statsvn" statvalue="64" type="cobertura-branch"/>
        <summaryresult date="2006-12-11" filecount="6" module="statsvn"
            project="statsvn" statvalue="12" type="pmd"/>
        <summaryresult date="2006-12-12" filecount="39" module="statsvn"
            project="statsvn" statvalue="17" type="checkstyle"/>
        <summaryresult date="2006-12-12" filecount="2" module="statsvn"
            project="statsvn" statvalue="2" type="findbugs"/>
        <summaryresult date="2006-12-12" filecount="1" module="statsvn"
            project="statsvn" statvalue="20" type="simian"/>
        <summaryresult date="2006-12-12" filecount="34" module="statsvn"
            project="statsvn" statvalue="59" type="cobertura-line"/>
        <summaryresult date="2006-12-12" filecount="34" module="statsvn"
            project="statsvn" statvalue="67" type="cobertura-branch"/>
        <summaryresult date="2006-12-12" filecount="1" module="statsvn"
            project="statsvn" statvalue="1" type="pmd"/>
        <summaryresult date="2006-12-26" filecount="39" module="statsvn"
            project="statsvn" statvalue="48" type="checkstyle"/>
        <summaryresult date="2006-12-26" filecount="3" module="statsvn"
            project="statsvn" statvalue="4" type="findbugs"/>
        <summaryresult date="2006-12-26" filecount="34" module="statsvn"
            project="statsvn" statvalue="57" type="cobertura-line"/>
        <summaryresult date="2006-12-26" filecount="34" module="statsvn"
            project="statsvn" statvalue="67" type="cobertura-branch"/>
        <summaryresult date="2006-12-26" filecount="4" module="statsvn"
            project="statsvn" statvalue="4" type="pmd"/>
        <summaryresult date="2007-01-03" filecount="40" module="statsvn"
            project="statsvn" statvalue="5" type="checkstyle"/>
        <summaryresult date="2007-01-03" filecount="3" module="statsvn"
            project="statsvn" statvalue="4" type="findbugs"/>
        <summaryresult date="2007-01-03" filecount="35" module="statsvn"
            project="statsvn" statvalue="57" type="cobertura-line"/>
        <summaryresult date="2007-01-03" filecount="35" module="statsvn"
            project="statsvn" statvalue="65" type="cobertura-branch"/>
        <summaryresult date="2007-01-08" filecount="40" module="statsvn"
            project="statsvn" statvalue="5" type="checkstyle"/>
        <summaryresult date="2007-01-08" filecount="3" module="statsvn"
            project="statsvn" statvalue="4" type="findbugs"/>
        <summaryresult date="2007-01-08" filecount="35" module="statsvn"
            project="statsvn" statvalue="56" type="cobertura-line"/>
        <summaryresult date="2007-01-08" filecount="35" module="statsvn"
            project="statsvn" statvalue="63" type="cobertura-branch"/>
        <summaryresult date="2007-01-10" filecount="41" module="statsvn"
            project="statsvn" statvalue="5" type="checkstyle"/>
        <summaryresult date="2007-01-10" filecount="2" module="statsvn"
            project="statsvn" statvalue="3" type="findbugs"/>
        <summaryresult date="2007-01-10" filecount="36" module="statsvn"
            project="statsvn" statvalue="53" type="cobertura-line"/>
        <summaryresult date="2007-01-10" filecount="36" module="statsvn"
            project="statsvn" statvalue="62" type="cobertura-branch"/>
        <summaryresult date="2007-01-12" filecount="41" module="statsvn"
            project="statsvn" statvalue="5" type="checkstyle"/>
        <summaryresult date="2007-01-12" filecount="2" module="statsvn"
            project="statsvn" statvalue="3" type="findbugs"/>
        <summaryresult date="2007-01-12" filecount="36" module="statsvn"
            project="statsvn" statvalue="51" type="cobertura-line"/>
        <summaryresult date="2007-01-12" filecount="36" module="statsvn"
            project="statsvn" statvalue="58" type="cobertura-branch"/>
        <summaryresult date="2007-01-19" filecount="41" module="statsvn"
            project="statsvn" statvalue="5" type="checkstyle"/>
        <summaryresult date="2007-01-19" filecount="2" module="statsvn"
            project="statsvn" statvalue="3" type="findbugs"/>
        <summaryresult date="2007-01-19" filecount="36" module="statsvn"
            project="statsvn" statvalue="51" type="cobertura-line"/>
        <summaryresult date="2007-01-19" filecount="36" module="statsvn"
            project="statsvn" statvalue="58" type="cobertura-branch"/>
        <summaryresult date="2007-02-07" filecount="41" module="statsvn"
            project="statsvn" statvalue="5" type="checkstyle"/>
        <summaryresult date="2007-02-07" filecount="2" module="statsvn"
            project="statsvn" statvalue="3" type="findbugs"/>
        <summaryresult date="2007-02-07" filecount="36" module="statsvn"
            project="statsvn" statvalue="51" type="cobertura-line"/>
        <summaryresult date="2007-02-07" filecount="36" module="statsvn"
            project="statsvn" statvalue="59" type="cobertura-branch"/>
        <summaryresult date="2007-03-08" filecount="42" module="statsvn"
            project="statsvn" statvalue="18" type="checkstyle"/>
        <summaryresult date="2007-03-08" filecount="3" module="statsvn"
            project="statsvn" statvalue="6" type="findbugs"/>
        <summaryresult date="2007-03-08" filecount="37" module="statsvn"
            project="statsvn" statvalue="52" type="cobertura-line"/>
        <summaryresult date="2007-03-08" filecount="37" module="statsvn"
            project="statsvn" statvalue="59" type="cobertura-branch"/>
        <summaryresult date="2007-03-08" filecount="1" module="statsvn"
            project="statsvn" statvalue="1" type="pmd"/>
        <summaryresult date="2007-03-09" filecount="42" module="statsvn"
            project="statsvn" statvalue="14" type="checkstyle"/>
        <summaryresult date="2007-03-09" filecount="3" module="statsvn"
            project="statsvn" statvalue="6" type="findbugs"/>
        <summaryresult date="2007-03-09" filecount="37" module="statsvn"
            project="statsvn" statvalue="54" type="cobertura-line"/>
        <summaryresult date="2007-03-09" filecount="37" module="statsvn"
            project="statsvn" statvalue="63" type="cobertura-branch"/>
        <summaryresult date="2007-03-09" filecount="1" module="statsvn"
            project="statsvn" statvalue="1" type="pmd"/>
        <summaryresult date="2007-03-11" filecount="42" module="statsvn"
            project="statsvn" statvalue="2" type="checkstyle"/>
        <summaryresult date="2007-03-11" filecount="2" module="statsvn"
            project="statsvn" statvalue="3" type="findbugs"/>
        <summaryresult date="2007-03-11" filecount="37" module="statsvn"
            project="statsvn" statvalue="53" type="cobertura-line"/>
        <summaryresult date="2007-03-11" filecount="37" module="statsvn"
            project="statsvn" statvalue="62" type="cobertura-branch"/>
        <summaryresult date="2007-03-12" filecount="42" module="statsvn"
            project="statsvn" statvalue="2" type="checkstyle"/>
        <summaryresult date="2007-03-12" filecount="2" module="statsvn"
            project="statsvn" statvalue="3" type="findbugs"/>
        <summaryresult date="2007-03-12" filecount="37" module="statsvn"
            project="statsvn" statvalue="54" type="cobertura-line"/>
        <summaryresult date="2007-03-12" filecount="37" module="statsvn"
            project="statsvn" statvalue="62" type="cobertura-branch"/>
        <summaryresult date="2007-03-14" filecount="42" module="statsvn"
            project="statsvn" statvalue="2" type="checkstyle"/>
        <summaryresult date="2007-03-14" filecount="2" module="statsvn"
            project="statsvn" statvalue="3" type="findbugs"/>
        <summaryresult date="2007-03-14" filecount="37" module="statsvn"
            project="statsvn" statvalue="54" type="cobertura-line"/>
        <summaryresult date="2007-03-14" filecount="37" module="statsvn"
            project="statsvn" statvalue="62" type="cobertura-branch"/>
        <summaryresult date="2007-03-30" filecount="42" module="statsvn"
            project="statsvn" statvalue="2" type="checkstyle"/>
        <summaryresult date="2007-03-30" filecount="3" module="statsvn"
            project="statsvn" statvalue="4" type="findbugs"/>
        <summaryresult date="2007-03-30" filecount="37" module="statsvn"
            project="statsvn" statvalue="55" type="cobertura-line"/>
        <summaryresult date="2007-03-30" filecount="37" module="statsvn"
            project="statsvn" statvalue="64" type="cobertura-branch"/>
        <summaryresult date="2007-04-06" filecount="42" module="statsvn"
            project="statsvn" statvalue="2" type="checkstyle"/>
        <summaryresult date="2007-04-06" filecount="3" module="statsvn"
            project="statsvn" statvalue="4" type="findbugs"/>
        <summaryresult date="2007-04-06" filecount="37" module="statsvn"
            project="statsvn" statvalue="55" type="cobertura-line"/>
        <summaryresult date="2007-04-06" filecount="37" module="statsvn"
            project="statsvn" statvalue="64" type="cobertura-branch"/>
        <summaryresult date="2008-03-31" filecount="39" module="statsvn"
            project="statsvn" statvalue="10" type="checkstyle"/>
        <summaryresult date="2008-03-31" filecount="2" module="statsvn"
            project="statsvn" statvalue="3" type="findbugs"/>
        <summaryresult date="2008-03-31" filecount="34" module="statsvn"
            project="statsvn" statvalue="48" type="cobertura-line"/>
        <summaryresult date="2008-03-31" filecount="34" module="statsvn"
            project="statsvn" statvalue="42" type="cobertura-branch"/>
        <summaryresult date="2008-03-31" filecount="1" module="statsvn"
            project="statsvn" statvalue="1" type="pmd"/>
        <summaryresult date="2008-05-04" filecount="39" module="statsvn"
            project="statsvn" statvalue="10" type="checkstyle"/>
        <summaryresult date="2008-05-04" filecount="2" module="statsvn"
            project="statsvn" statvalue="3" type="findbugs"/>
        <summaryresult date="2008-05-04" filecount="34" module="statsvn"
            project="statsvn" statvalue="47" type="cobertura-line"/>
        <summaryresult date="2008-05-04" filecount="34" module="statsvn"
            project="statsvn" statvalue="41" type="cobertura-branch"/>
        <summaryresult date="2008-05-04" filecount="1" module="statsvn"
            project="statsvn" statvalue="1" type="pmd"/>
        <summaryresult date="2008-06-17" filecount="39" module="statsvn"
            project="statsvn" statvalue="11" type="checkstyle"/>
        <summaryresult date="2008-06-17" filecount="2" module="statsvn"
            project="statsvn" statvalue="3" type="findbugs"/>
        <summaryresult date="2008-06-17" filecount="34" module="statsvn"
            project="statsvn" statvalue="47" type="cobertura-line"/>
        <summaryresult date="2008-06-17" filecount="34" module="statsvn"
            project="statsvn" statvalue="39" type="cobertura-branch"/>
        <summaryresult date="2008-06-17" filecount="1" module="statsvn"
            project="statsvn" statvalue="1" type="pmd"/>
        <summaryresult date="2008-06-25" filecount="39" module="statsvn"
            project="statsvn" statvalue="3" type="checkstyle"/>
        <summaryresult date="2008-06-25" filecount="2" module="statsvn"
            project="statsvn" statvalue="3" type="findbugs"/>
        <summaryresult date="2008-06-25" filecount="34" module="statsvn"
            project="statsvn" statvalue="47" type="cobertura-line"/>
        <summaryresult date="2008-06-25" filecount="34" module="statsvn"
            project="statsvn" statvalue="40" type="cobertura-branch"/>
        <summaryresult date="2008-07-15" filecount="39" module="statsvn"
            project="statsvn" statvalue="2" type="checkstyle"/>
        <summaryresult date="2008-07-15" filecount="2" module="statsvn"
            project="statsvn" statvalue="3" type="findbugs"/>
        <summaryresult date="2008-07-15" filecount="34" module="statsvn"
            project="statsvn" statvalue="47" type="cobertura-line"/>
        <summaryresult date="2008-07-15" filecount="34" module="statsvn"
            project="statsvn" statvalue="40" type="cobertura-branch"/>
        <summaryresult date="2009-02-21" filecount="39" module="statsvn"
            project="statsvn" statvalue="2" type="checkstyle"/>
        <summaryresult date="2009-02-21" filecount="2" module="statsvn"
            project="statsvn" statvalue="3" type="findbugs"/>
        <summaryresult date="2009-02-21" filecount="34" module="statsvn"
            project="statsvn" statvalue="47" type="cobertura-line"/>
        <summaryresult date="2009-02-21" filecount="34" module="statsvn"
            project="statsvn" statvalue="40" type="cobertura-branch"/>
        <summaryresult date="2009-02-24" filecount="39" module="statsvn"
            project="statsvn" statvalue="2" type="checkstyle"/>
        <summaryresult date="2009-02-24" filecount="2" module="statsvn"
            project="statsvn" statvalue="3" type="findbugs"/>
        <summaryresult date="2009-02-24" filecount="34" module="statsvn"
            project="statsvn" statvalue="47" type="cobertura-line"/>
        <summaryresult date="2009-02-24" filecount="34" module="statsvn"
            project="statsvn" statvalue="40" type="cobertura-branch"/>
        <summaryresult date="2009-03-09" filecount="39" module="statsvn"
            project="statsvn" statvalue="2" type="checkstyle"/>
        <summaryresult date="2009-03-09" filecount="2" module="statsvn"
            project="statsvn" statvalue="3" type="findbugs"/>
        <summaryresult date="2009-03-09" filecount="34" module="statsvn"
            project="statsvn" statvalue="47" type="cobertura-line"/>
        <summaryresult date="2009-03-09" filecount="34" module="statsvn"
            project="statsvn" statvalue="40" type="cobertura-branch"/>
        <summaryresult date="2009-03-10" filecount="39" module="statsvn"
            project="statsvn" statvalue="2" type="checkstyle"/>
        <summaryresult date="2009-03-10" filecount="2" module="statsvn"
            project="statsvn" statvalue="3" type="findbugs"/>
        <summaryresult date="2009-03-10" filecount="34" module="statsvn"
            project="statsvn" statvalue="47" type="cobertura-line"/>
        <summaryresult date="2009-03-10" filecount="34" module="statsvn"
            project="statsvn" statvalue="40" type="cobertura-branch"/>
        <summaryresult date="2009-03-11" filecount="39" module="statsvn"
            project="statsvn" statvalue="2" type="checkstyle"/>
        <summaryresult date="2009-03-11" filecount="3" module="statsvn"
            project="statsvn" statvalue="4" type="findbugs"/>
        <summaryresult date="2009-03-11" filecount="34" module="statsvn"
            project="statsvn" statvalue="47" type="cobertura-line"/>
        <summaryresult date="2009-03-11" filecount="34" module="statsvn"
            project="statsvn" statvalue="40" type="cobertura-branch"/>
        <summaryresult date="2009-03-12" filecount="39" module="statsvn"
            project="statsvn" statvalue="2" type="checkstyle"/>
        <summaryresult date="2009-03-12" filecount="3" module="statsvn"
            project="statsvn" statvalue="4" type="findbugs"/>
        <summaryresult date="2009-03-12" filecount="34" module="statsvn"
            project="statsvn" statvalue="47" type="cobertura-line"/>
        <summaryresult date="2009-03-12" filecount="34" module="statsvn"
            project="statsvn" statvalue="40" type="cobertura-branch"/>
        <summaryresult date="2009-03-13" filecount="39" module="statsvn"
            project="statsvn" statvalue="2" type="checkstyle"/>
        <summaryresult date="2009-03-13" filecount="3" module="statsvn"
            project="statsvn" statvalue="4" type="findbugs"/>
        <summaryresult date="2009-03-13" filecount="34" module="statsvn"
            project="statsvn" statvalue="47" type="cobertura-line"/>
        <summaryresult date="2009-03-13" filecount="34" module="statsvn"
            project="statsvn" statvalue="40" type="cobertura-branch"/>
        <summaryresult date="2009-03-14" filecount="39" module="statsvn"
            project="statsvn" statvalue="2" type="checkstyle"/>
        <summaryresult date="2009-03-14" filecount="3" module="statsvn"
            project="statsvn" statvalue="4" type="findbugs"/>
        <summaryresult date="2009-03-14" filecount="34" module="statsvn"
            project="statsvn" statvalue="47" type="cobertura-line"/>
        <summaryresult date="2009-03-14" filecount="34" module="statsvn"
            project="statsvn" statvalue="40" type="cobertura-branch"/>
        <summaryresult date="2009-04-25" filecount="42" module="statsvn"